FROM balenalib/%%BALENA_MACHINE_NAME%%-python

# install ruby or whatever
RUN apt-get update && apt-get install -yq --no-install-recommends \
    ruby \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

# pip install python deps from requirements.txt
# For caching until requirements.txt changes
COPY ./requirements.txt /requirements.txt
RUN READTHEDOCS=True pip install -r /requirements.txt

COPY . /usr/src/app
WORKDIR /usr/src/app

CMD ["bash","start.sh"]

